# Generated by Django 4.1.7 on 2023-02-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_username', models.CharField(max_length=100)),
                ('user_passportnumber', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_contact', models.CharField(max_length=15)),
                ('user_address', models.TextField()),
                ('user_image', models.ImageField(upload_to='user/images')),
            ],
            options={
                'db_table': 'User_Details',
            },
        ),
    ]
