# Generated by Django 4.1.7 on 2023-02-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user_address',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_passportnumber',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_dob',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_occupation',
            field=models.TextField(null=True),
        ),
    ]
