# Generated by Django 4.1.7 on 2023-02-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_usermodel_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_status',
            field=models.CharField(default='pending', help_text='user_status', max_length=50, null=True),
        ),
    ]
