# Generated by Django 4.1.7 on 2023-02-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('job_dept', models.CharField(max_length=100)),
                ('job_com_profile', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=100)),
                ('job_requirement', models.CharField(max_length=100)),
                ('job_benefits', models.CharField(max_length=100)),
                ('job_req_experience', models.CharField(max_length=100)),
                ('job_req_education', models.CharField(max_length=100)),
                ('job_industry', models.CharField(max_length=100)),
                ('job_function', models.CharField(max_length=100)),
                ('job_salary_range', models.CharField(max_length=100)),
                ('job_emp_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'job_Details',
            },
        ),
    ]
