# Generated by Django 4.1.7 on 2023-02-20 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_usermodel_user_status'),
        ('userapp', '0002_jobmodel_user_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictModel',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('job_dept', models.CharField(max_length=100)),
                ('job_com_profile', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=100)),
                ('job_requirement', models.CharField(max_length=100)),
                ('job_benefits', models.CharField(max_length=100)),
                ('job_req_experience', models.CharField(max_length=100)),
                ('job_req_education', models.CharField(max_length=100)),
                ('job_industry', models.CharField(max_length=100)),
                ('job_function', models.CharField(max_length=100)),
                ('job_salary_range', models.CharField(max_length=100)),
                ('job_emp_type', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_url_id', to='mainapp.usermodel')),
            ],
            options={
                'db_table': 'predict_Details',
            },
        ),
    ]
