# Generated by Django 4.1.7 on 2023-02-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_predictmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='job_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
