# Generated by Django 4.1.7 on 2023-02-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_jobmodel_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='job_benefits',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_com_profile',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_dept',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_emp_type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_function',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_industry',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_location',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_req_education',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_req_experience',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_requirement',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_salary_range',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_title',
            field=models.CharField(max_length=500),
        ),
    ]
